name: Build iperf3 Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-iperf3

    - name: Copy exe
      shell: msys2 {0}
      run: |
        cp /mingw64/bin/iperf3.exe .

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: iperf3-windows
        path: iperf3.exe
